logger:
  level: "INFO" # ERROR|WARNING|INFO|DEBUG
  path: "./logs/calendar.log"

storage:
  type: "memory" # memory|sql

http:
  host: "localhost"
  port: 8080

# Check: curl -v --http2-prior-knowledge http://localhost:50051/
grpc:
  host: "localhost"
  port: 50051

# Конфигурация db необходима, если storage.type - это sql
db:
  dbhost: "localhost"
  dbport: 5435
  dbname: "backend"
  dbusername: "postgres"
  dbpassword: "password"