apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-calendar-api
  labels:
    {{- include "calendar-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: calendar-api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.api.service.grpcPort }}
      targetPort: grpc
  selector:
    app.kubernetes.io/component: calendar-api
    app.kubernetes.io/instance: {{ .Release.Name }}
