// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: calendar/v1/calendar.proto

package calendarv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event — сущность календаря; вынесена в отдельное сообщение (message), т.к. повторяется во многих ответах.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// date_time — начало события.
	DateTime string `protobuf:"bytes,3,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	// duration — длительность в секундах.
	Duration    int64  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId      string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// notification_time — момент уведомления (пустая строка, если не задано).
	NotificationTime string `protobuf:"bytes,7,opt,name=notification_time,json=notificationTime,proto3" json:"notification_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDateTime() string {
	if x != nil {
		return x.DateTime
	}
	return ""
}

func (x *Event) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetNotificationTime() string {
	if x != nil {
		return x.NotificationTime
	}
	return ""
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{6}
}

type ListEventsForDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForDayRequest) Reset() {
	*x = ListEventsForDayRequest{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForDayRequest) ProtoMessage() {}

func (x *ListEventsForDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForDayRequest.ProtoReflect.Descriptor instead.
func (*ListEventsForDayRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{7}
}

func (x *ListEventsForDayRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *ListEventsForDayRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListEventsForWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekStart     string                 `protobuf:"bytes,1,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForWeekRequest) Reset() {
	*x = ListEventsForWeekRequest{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForWeekRequest) ProtoMessage() {}

func (x *ListEventsForWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForWeekRequest.ProtoReflect.Descriptor instead.
func (*ListEventsForWeekRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{8}
}

func (x *ListEventsForWeekRequest) GetWeekStart() string {
	if x != nil {
		return x.WeekStart
	}
	return ""
}

func (x *ListEventsForWeekRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListEventsForMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonthStart    string                 `protobuf:"bytes,1,opt,name=month_start,json=monthStart,proto3" json:"month_start,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsForMonthRequest) Reset() {
	*x = ListEventsForMonthRequest{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsForMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsForMonthRequest) ProtoMessage() {}

func (x *ListEventsForMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsForMonthRequest.ProtoReflect.Descriptor instead.
func (*ListEventsForMonthRequest) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{9}
}

func (x *ListEventsForMonthRequest) GetMonthStart() string {
	if x != nil {
		return x.MonthStart
	}
	return ""
}

func (x *ListEventsForMonthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_calendar_v1_calendar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calendar_v1_calendar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_calendar_v1_calendar_proto_rawDescGZIP(), []int{10}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_calendar_v1_calendar_proto protoreflect.FileDescriptor

const file_calendar_v1_calendar_proto_rawDesc = "" +
	"\n" +
	"\x1acalendar/v1/calendar.proto\x12\vcalendar.v1\"\xce\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tdate_time\x18\x03 \x01(\tR\bdateTime\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12+\n" +
	"\x11notification_time\x18\a \x01(\tR\x10notificationTime\">\n" +
	"\x12CreateEventRequest\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.calendar.v1.EventR\x05event\"?\n" +
	"\x13CreateEventResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.calendar.v1.EventR\x05event\"N\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x05event\x18\x02 \x01(\v2\x12.calendar.v1.EventR\x05event\"?\n" +
	"\x13UpdateEventResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.calendar.v1.EventR\x05event\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteEventResponse\"D\n" +
	"\x17ListEventsForDayRequest\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"R\n" +
	"\x18ListEventsForWeekRequest\x12\x1d\n" +
	"\n" +
	"week_start\x18\x01 \x01(\tR\tweekStart\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"U\n" +
	"\x19ListEventsForMonthRequest\x12\x1f\n" +
	"\vmonth_start\x18\x01 \x01(\tR\n" +
	"monthStart\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"@\n" +
	"\x12ListEventsResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.calendar.v1.EventR\x06events2\x9e\x04\n" +
	"\x0fCalendarService\x12P\n" +
	"\vCreateEvent\x12\x1f.calendar.v1.CreateEventRequest\x1a .calendar.v1.CreateEventResponse\x12P\n" +
	"\vUpdateEvent\x12\x1f.calendar.v1.UpdateEventRequest\x1a .calendar.v1.UpdateEventResponse\x12P\n" +
	"\vDeleteEvent\x12\x1f.calendar.v1.DeleteEventRequest\x1a .calendar.v1.DeleteEventResponse\x12Y\n" +
	"\x10ListEventsForDay\x12$.calendar.v1.ListEventsForDayRequest\x1a\x1f.calendar.v1.ListEventsResponse\x12[\n" +
	"\x11ListEventsForWeek\x12%.calendar.v1.ListEventsForWeekRequest\x1a\x1f.calendar.v1.ListEventsResponse\x12]\n" +
	"\x12ListEventsForMonth\x12&.calendar.v1.ListEventsForMonthRequest\x1a\x1f.calendar.v1.ListEventsResponseBYZWgithub.com/kodmandvl/go-hw/hw12_13_14_15_16_calendar/internal/pb/calendar/v1;calendarv1b\x06proto3"

var (
	file_calendar_v1_calendar_proto_rawDescOnce sync.Once
	file_calendar_v1_calendar_proto_rawDescData []byte
)

func file_calendar_v1_calendar_proto_rawDescGZIP() []byte {
	file_calendar_v1_calendar_proto_rawDescOnce.Do(func() {
		file_calendar_v1_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calendar_v1_calendar_proto_rawDesc), len(file_calendar_v1_calendar_proto_rawDesc)))
	})
	return file_calendar_v1_calendar_proto_rawDescData
}

var file_calendar_v1_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_calendar_v1_calendar_proto_goTypes = []any{
	(*Event)(nil),                     // 0: calendar.v1.Event
	(*CreateEventRequest)(nil),        // 1: calendar.v1.CreateEventRequest
	(*CreateEventResponse)(nil),       // 2: calendar.v1.CreateEventResponse
	(*UpdateEventRequest)(nil),        // 3: calendar.v1.UpdateEventRequest
	(*UpdateEventResponse)(nil),       // 4: calendar.v1.UpdateEventResponse
	(*DeleteEventRequest)(nil),        // 5: calendar.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),       // 6: calendar.v1.DeleteEventResponse
	(*ListEventsForDayRequest)(nil),   // 7: calendar.v1.ListEventsForDayRequest
	(*ListEventsForWeekRequest)(nil),  // 8: calendar.v1.ListEventsForWeekRequest
	(*ListEventsForMonthRequest)(nil), // 9: calendar.v1.ListEventsForMonthRequest
	(*ListEventsResponse)(nil),        // 10: calendar.v1.ListEventsResponse
}
var file_calendar_v1_calendar_proto_depIdxs = []int32{
	0,  // 0: calendar.v1.CreateEventRequest.event:type_name -> calendar.v1.Event
	0,  // 1: calendar.v1.CreateEventResponse.event:type_name -> calendar.v1.Event
	0,  // 2: calendar.v1.UpdateEventRequest.event:type_name -> calendar.v1.Event
	0,  // 3: calendar.v1.UpdateEventResponse.event:type_name -> calendar.v1.Event
	0,  // 4: calendar.v1.ListEventsResponse.events:type_name -> calendar.v1.Event
	1,  // 5: calendar.v1.CalendarService.CreateEvent:input_type -> calendar.v1.CreateEventRequest
	3,  // 6: calendar.v1.CalendarService.UpdateEvent:input_type -> calendar.v1.UpdateEventRequest
	5,  // 7: calendar.v1.CalendarService.DeleteEvent:input_type -> calendar.v1.DeleteEventRequest
	7,  // 8: calendar.v1.CalendarService.ListEventsForDay:input_type -> calendar.v1.ListEventsForDayRequest
	8,  // 9: calendar.v1.CalendarService.ListEventsForWeek:input_type -> calendar.v1.ListEventsForWeekRequest
	9,  // 10: calendar.v1.CalendarService.ListEventsForMonth:input_type -> calendar.v1.ListEventsForMonthRequest
	2,  // 11: calendar.v1.CalendarService.CreateEvent:output_type -> calendar.v1.CreateEventResponse
	4,  // 12: calendar.v1.CalendarService.UpdateEvent:output_type -> calendar.v1.UpdateEventResponse
	6,  // 13: calendar.v1.CalendarService.DeleteEvent:output_type -> calendar.v1.DeleteEventResponse
	10, // 14: calendar.v1.CalendarService.ListEventsForDay:output_type -> calendar.v1.ListEventsResponse
	10, // 15: calendar.v1.CalendarService.ListEventsForWeek:output_type -> calendar.v1.ListEventsResponse
	10, // 16: calendar.v1.CalendarService.ListEventsForMonth:output_type -> calendar.v1.ListEventsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_calendar_v1_calendar_proto_init() }
func file_calendar_v1_calendar_proto_init() {
	if File_calendar_v1_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calendar_v1_calendar_proto_rawDesc), len(file_calendar_v1_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calendar_v1_calendar_proto_goTypes,
		DependencyIndexes: file_calendar_v1_calendar_proto_depIdxs,
		MessageInfos:      file_calendar_v1_calendar_proto_msgTypes,
	}.Build()
	File_calendar_v1_calendar_proto = out.File
	file_calendar_v1_calendar_proto_goTypes = nil
	file_calendar_v1_calendar_proto_depIdxs = nil
}
